module.exports = {
  title: "Hexo",
  url: "https://rustiebeats.github.io",
  author: "John Doe",
  description: "",
  header_title: "Hi Folks.",
  owner: "Rustiebeats.github.io",
  email: "",
  info: "Problem Solver",
  desc: "Problem Solver",
  menu: {
    Blog: "/blog/",
    About: "/about/",
  },
  max_post: 4,
  tcolor: "0FA0CE",
  footer: true,
  github: "https://github.com/rustiebeats",
  linkedin: "",
  twitter: "",
  instagram: "",
  switch_light: "☀️",
  switch_dark: "🌑",
};
